// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for web platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvXK-1EVaATpjUh4S1Ei4AspR-mMgt3c',
    appId: '1:407808580024:android:e59ca46c5395dcd540174d',
    messagingSenderId: '407808580024',
    projectId: 'qr-barcode-scanner-c4cd7',
    storageBucket: 'qr-barcode-scanner-c4cd7.firebasestorage.app',
  );
}
